addons:
  sonarcloud:
    organization: "sargue-github" # the key of the org you chose at step #3
    token:
      secure: "UxKsjtCqrwW04QB+d5dtduAhbNEDwwl1sQFObpof+vi6bezXBDK6ZUIq2JsoD6Gtqn1ak8lNnfq1K9ln4lUnBO3PncOJsKCwio6F7YhTc9QCwqwBZ8pNowC9SY//e9Hzoa2WdavAlmH5SlQvEYfZdy/2cWXJmq320eD2Az0dwiUhNrnvdJYwgMityCTaxNIsWU/w2gPl4hd6pM9JJbISUivfvQ2kV4hCMC81ksgeqRh3DuuqqBNUgOo+M/Va/QcMFGLpTYUq7OkcHLHN3NrF0IGkv6Cf9uU2d1jaHRH/zqD5nmQOMuml/uEeOkYogok1I+rBXfwAG7gdnB7FXW/11LNoIH3rO5aqeXXBm9UOC4tqDD0BExMS05Sr/yUGcV0dndY9vQRhuiR27I087TU6PXtWjgxyYOSwbhpqfx8vBKsQQHvSUgNPP8b664cWHJAe19Nam3wPyuVPB94xwudDUoWIqEVEDPTZuR5QfzZucppKo6zvFqoN0RyA9/+1NhAdLBszbIOXDQ3j3L4ID+rPvVlRQctnXER9TX1IRqlLd6SQMhp+Qo752sbTtWbaJ3seanHfM4MXRCuZUwoxuLlZO3v7/caNRr9G0pNeZIt/H2OusAeeWYJgsu5DsHPzIVO1N17jtt7Dg9eVa8GjkjiowxRC+qqjVJViRldmeFfr608="
jdk:
  - oraclejdk8
language: java
install: /bin/true
before_install:
 - chmod +x gradlew
script:
 - ./gradlew check
 - sonar-scanner
